DataFolder = "/data/data/com.termux/files/home/navidrome/data"
MusicFolder = "/data/data/com.termux/files/home/music"
EnableTranscodingConfig=false
Spotify.ID = "9e61495eedf1400aab1e579bc721adc3"
Spotify.Secret = "4216bf5516bc457cb8939a12b889ebf4"